
net = googlenet;
inputSize = net.Layers(1).InputSize;

% Defining Calorie Lookup Table
calorieTable = containers.Map( ...
    {'cheeseburger', 'chicken burger', 'veg burger', 'chicken wrap', ...
     'veg wrap', 'chicken nuggets', 'hot dog', 'tacos', 'shawarma', ...
     'fried chicken', 'grilled chicken', 'paneer wrap', ...
     'subway sandwich', 'chocolate donut', 'ice cream', ...
     'milkshake', 'cold coffee', 'maggi', ...
     'hakka noodles', 'manchurian', 'pizza', ...
     'burger', 'pasta', 'sandwich', 'french fries', 'fried rice', ...
     'noodles', 'biryani', 'roti', 'paratha', 'idli', 'dosa', 'vada', ...
     'samosa', 'paneer tikka', 'butter chicken', 'dal', 'rice', ...
     'curd', 'salad', 'apple'}, ...
    [302, 290, 275, 236, ...
     195, 296, 290, 226, 240, ...
     320, 165, 270, ...
     210, 452, 207, ...
     208, 97, 370, ...
     180, 250, 266, 295, 131, 250, 312, 168, ...
     138, 222, 120, 260, 70, 165, 250, ...
     262, 265, 290, 116, 130, ...
     98, 52, 52]);
  % kcal per 100g

% input
[file, path] = uigetfile('*.jpg', 'Select a food image');
if isequal(file,0)
    disp('No image selected.');
    return;
end
img = imread(fullfile(path, file));

% Resize and Classify
imgResized = imresize(img, inputSize(1:2));
[label, ~] = classify(net, imgResized);
predictedFood = lower(string(label));

% compare
if isKey(calorieTable, predictedFood)
    calories = calorieTable(predictedFood);
    msg = sprintf('Food: %s\nCalories: %d kcal/100g', predictedFood, calories);
else
    msg = sprintf('Food: %s\nCalories: Unknown', predictedFood);
end

% Display Image and Result
imshow(img);
title(msg);
